name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python environment
      uses: ./.github/actions/setup-python-env
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "test_*.py" -v

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python environment
      uses: ./.github/actions/setup-python-env
      with:
        install-requirements: 'false'
        extra-dependencies: 'flake8 pylint'

    - name: Lint with flake8
      run: |
        # Check for all linting issues including syntax errors and PEP 8 style violations
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics --exclude=__pycache__,_esp32,.venv

  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python environment
      uses: ./.github/actions/setup-python-env
      with:
        extra-dependencies: 'pip-audit bandit'

    - name: Security check with bandit
      run: |
        bandit -r . -f json -o bandit-report.json --exclude=./_esp32,./tests || true
        bandit -r . --exclude=./_esp32,./tests

    - name: Check dependencies with pip-audit
      run: |
        pip-audit --requirement requirements.txt --format json || true
        pip-audit --requirement requirements.txt

  build-status:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: always()

    steps:
    - name: Check build status
      run: |
        if [ "${{ needs.test.result }}" = "failure" ] || [ "${{ needs.lint.result }}" = "failure" ]; then
          echo "Build failed!"
          exit 1
        else
          echo "Build passed!"
        fi
